# TIP: Variables from this file can be accessed from template files with: {{ site.variable }}. For example: {{ site.title }} or {{ site.description }}
# You'll want to modify most of this file with your own branding and links.

title: "JAM Stack e-commerce template" # Appears after the title Page eg. Title - Web Starter
subtitle: "Making fundraising easy!"
description: "An e-commerce website built with 11ty.js, TailwindCSS and Foxy.io" # Used in the meta tags, for search engines and social sharing
url: "https://foxy.io/" # Set this to the domain you'll publish this site to
author: "Foxy.io" # This is used for the copyright notice in the footer
meta_data:
  twitter: "@foxycart" # Used in the meta tags
  default_social_image: "/static/logo.png"

# Careful! Use quotes around your links.
# You can add additional nav items, and the urls can be external links.
navigation:
  - name: Welcome
    url: "#welcome"
    description: Return to the top
  - name: About
    url: "#about"
    description: Learn about what we're doing
  - name: Donate!
    url: "#donate"
    description: Help support us
  - name: Needed items
    url: "#items"
    description: Help with a specific item

# The following are the headings for the navigation
texts:
  highlights_title: "Here are some of our highlights"
  highlights_text: "Click the links below to load the videos while you browse."
  about_title: "About Us" # This the heading for the 2nd section, if desired.
  donate_title: "Donate"
  needed_items_title: "Needed Items" # This is the heading for the products / donation items.

currency_symbol: $
currency: usd

donation_form:
  name: "One-Time Donation" # this field is required
  amount: 100 # this field is required
  # fields bellow can be ommited to stop the form from using them
  # you can simply delete them, but it would be best to simply comment it out so you can bring it back if you wish.
  amounts: "[25, 50, 100, 500,1000]" # must be in JSON format
  anonymity: false
  comment: false
  custom: '["amount", "designation"]' # must be in JSON format
  designation: '["Area of Greatest Need"]' # must be in JSON format. Sets the default designation value.
  designations: '["Area of Greatest Need", "Medical Aid", "Economic Relief"]' # Sets the degination options.
  frequencies: '["0d", "1m", "2m", "3m"]' # must be in JSON format. Sets the frequencies options.
  frequency: "1m" # set the default frequency option
  # use 1d for 1 per day (daily contributions)
  # use 1w for 1 per week (weekly contributions)
  # use 1m for 1 per month (monthly contributions)
  # use 1y for 1 per year (yearly contributions)

# Careful! Use quotes around your links.
social_networks:
  blog:
    url: "https://www.foxy.io/blog/"
    icon: "fas fa-blog-square"
  email:
    url: "mailto:hello@example.com"
    icon: "fas fa-envelope-square"
    protocol: "mailto"
  facebook:
    url: "https://www.facebook.com/foxycart"
    icon: "fab fa-facebook-square"
  twitter:
    url: "https://twitter.com/foxycart"
    icon: "fab fa-twitter-square"
  youtube:
    url: "https://www.youtube.com/foxycart"
    icon: "fab fa-youtube"
